### ISSUE TITLE
Which python version is the tool best compatible with?

### ISSUE THREAD

**Issue by ivanayov** [nexB/tracecode-toolkit-strace#5]
Hi,

I'm testing the tool on Ubuntu 18.
With python 3.6 I had the following issue from `./configure --dev`:
```
ModuleNotFoundError: No module named 'importlib.resources'
```

I updated to 3.10 and `./configure --dev` worked well.

Then I tried to `pip3 install apt_pkg` as ` tracecode -h` was failing with `ModuleNotFoundError: No module named 'apt_pkg'` and got the following:
```
AttributeError: module 'collections' has no attribute 'MutableMapping'
```
which is a result of updating `collections.MutableMapping` to `collections.abc.MutableMapping` in 3.10.

  

Then I downgraded to 3.9 and couldn't run again `./configure --dev`, as for
```
ModuleNotFoundError: No module named 'pip'
```
which I'm not sure how to fix in `tracecode`'s setup.

`pip3 install apt_pkg` failed for all 3.9, 3.8 and 3.7 with:
```
Could not find a version that satisfies the requirement apt_pkg (from versions: )
No matching distribution found for apt_pkg
```
  

How can I clean up the whole installation and start from scratch and which python version should I use?

Thanks :)

**Comment by pombredanne** [comment]
@ivanayov Hey :wave: thanks! This is a bug alright

... it should work fine with Python 3.9 and we test it on 3.8, 3.9 and 3.10 ... all tests pass as you can see here https://dev.azure.com/nexB/tracecode-toolkit-strace/_build/results?buildId=9563&view=logs&j=0cfca3bc-aa91-566e-292e-f125b0e3456a

But there is a quirk in the syntax for the python_requires in the setup.cfg that showed in recent version of setup tools and pip.
I am fixing this in https://github.com/nexB/tracecode-toolkit-strace/tree/latest-skeleton

**Comment by pombredanne** [comment]
This should not have been closed. %^$%^$ to github!
FWIW the culprit is a change in the packaging library that occurred here https://github.com/pypa/packaging/compare/21.3...23.0
